# Generated by Django 4.1.5 on 2023-01-17 22:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='1920x801 px image for fit background', upload_to='about')),
                ('about', ckeditor.fields.RichTextField()),
                ('firstprocess', ckeditor.fields.RichTextField(max_length=600)),
                ('secondprocess', ckeditor.fields.RichTextField(max_length=600)),
                ('thirdprocess', ckeditor.fields.RichTextField(max_length=600)),
                ('fourthprocess', ckeditor.fields.RichTextField(max_length=600)),
            ],
        ),
    ]
