# Generated by Django 4.1.5 on 2023-01-18 20:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_about_stage_four_title_about_stage_one_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='1920x801 px image for fit background', upload_to='about')),
                ('about', ckeditor.fields.RichTextField()),
                ('stage_one_title', models.CharField(max_length=100, null=True)),
                ('firstprocess', ckeditor.fields.RichTextField(blank=True, max_length=600)),
                ('stage_two_title', models.CharField(max_length=100, null=True)),
                ('secondprocess', ckeditor.fields.RichTextField(blank=True, max_length=600)),
                ('stage_three_title', models.CharField(max_length=100, null=True)),
                ('thirdprocess', ckeditor.fields.RichTextField(blank=True, max_length=600)),
                ('stage_four_title', models.CharField(max_length=100, null=True)),
                ('fourthprocess', ckeditor.fields.RichTextField(blank=True, max_length=600)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='firstprocess',
        ),
        migrations.RemoveField(
            model_name='about',
            name='fourthprocess',
        ),
        migrations.RemoveField(
            model_name='about',
            name='secondprocess',
        ),
        migrations.RemoveField(
            model_name='about',
            name='stage_four_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='stage_one_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='stage_three_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='stage_two_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='thirdprocess',
        ),
    ]
