# Generated by Django 4.1.5 on 2023-01-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
