# Generated by Django 4.1.5 on 2023-01-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_service_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='is_closed',
            new_name='is_active',
        ),
    ]
