# Generated by Django 4.1.5 on 2023-01-20 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_offer_id_offer_slug_offer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
