# Generated by Django 4.1.5 on 2023-01-20 13:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_offer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='about',
        ),
        migrations.RemoveField(
            model_name='service',
            name='firstprocess',
        ),
        migrations.RemoveField(
            model_name='service',
            name='fourthprocess',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='secondprocess',
        ),
        migrations.RemoveField(
            model_name='service',
            name='stage_four_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='stage_one_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='stage_three_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='stage_two_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='thirdprocess',
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(help_text='1920x801 px image for fit background', null=True, upload_to='services'),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
