# Generated by Django 4.1.5 on 2023-01-20 14:21

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_service_about_remove_service_firstprocess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.FileField(help_text='1920x801 px image for fit background', null=True, upload_to=website.models.upload_to),
        ),
    ]
