# Generated by Django 4.1.5 on 2023-01-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_image', models.ImageField(help_text='1920x801 px image for fit background', upload_to='logo')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
