# Generated by Django 4.1.5 on 2025-05-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_jobphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobphoto',
            name='job_image',
            field=models.ImageField(help_text='1920x801 px image for fit background', upload_to='jobad'),
        ),
    ]
