# Generated by Django 4.1.5 on 2023-01-18 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_applicant_cover_letter_alter_applicant_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 17, 0, 6, 31, 198087), help_text='By default its set after 30 days but this can be changed'),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
