# Generated by Django 4.1.5 on 2023-01-18 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_job_last_date_alter_job_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 17, 0, 23, 26, 84325), help_text='By default its set after 30 days but this can be changed'),
        ),
    ]
