# Generated by Django 4.1.5 on 2023-01-18 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_alter_job_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 17, 21, 32, 20, 568538), help_text='By default its set after 30 days but this can be changed'),
        ),
    ]
