# Generated by Django 4.1.5 on 2023-01-19 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_alter_job_last_date_alter_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 18, 16, 54, 59, 296359), help_text='By default its set after 30 days but this can be changed'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(choices=[('Confidential', 'Confidential'), (10000, '10,000 - 30,000 KES'), (31000, '31,000 - 60,000 KES'), (61000, '61,000 - 90,000 KES'), (91000, '91,000 - 120,000 KES'), (121000, '121,000 - 150,000 KES'), (151000, '151,000 - 180,000 KES'), (181000, '181,000 - 210,000 KES'), (211000, '211,000 - 240,000 KES'), (241000, '241,000 - 270,000 KES'), (271000, '271,000 - 300,000 KES'), (301000, '301,000 - 330,000 KES'), (331000, '331,000 - 360,000 KES'), (361000, '361,000 - 390,000 KES'), (391000, '391,000 - 420,000 KES'), (421000, '421,000 - 450,000 KES'), (451000, '451,000 - 480,000 KES'), (481000, '481,000 - 510,000 KES'), (511000, '511,000 - 540,000 KES'), (541000, '541,000 - 570,000 KES'), (571000, '571,000 - 600,000 KES'), (601000, '601,000 - 630,000 KES'), (631000, '631,000 - 660,000 KES'), (661000, '661,000 - 690,000 KES'), (691000, '691,000 - 720,000 KES'), (721000, '721,000 - 750,000 KES'), (751000, '751,000 - 780,000 KES'), (781000, '781,000 - 810,000 KES'), (811000, '811,000 - 840,000 KES'), (841000, '841,000 - 870,000 KES'), (871000, '871,000 - 900,000 KES'), (901000, '901,000 - 930,000 KES'), (931000, '931,000 - 960,000 KES'), (961000, '961,000 - 990,000 KES'), (991000, '991,000 - 1,000,000 KES')], default=0),
        ),
    ]
