# Generated by Django 4.1.5 on 2023-01-19 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_alter_job_last_date_alter_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 18, 17, 0, 12, 981883), help_text='By default its set after 30 days but this can be changed'),
        ),
    ]
