# Generated by Django 4.1.5 on 2023-01-19 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_alter_job_job_type_alter_job_last_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 18, 17, 45, 22, 760231), help_text='By default its set after 30 days but this can be changed'),
        ),
    ]
