# Generated by Django 4.1.5 on 2023-01-20 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0026_alter_job_category_alter_job_last_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Information Technology', 'Information Technology'), ('Human Resources', 'Human Resources'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Sales', 'Sales'), ('Management', 'Management'), ('Teaching and Learning', 'Teaching and Learning'), ('Engineering', 'Engineering'), ('Medical and Health', 'Medical and Health'), ('Science', 'Science'), ('Art and Design', 'Art and Design'), ('Legal', 'Legal'), ('Transportation', 'Transportation'), ('Construction', 'Construction'), ('Cleaning', 'Cleaning'), ('Agriculture', 'Agriculture'), ('Food Service', 'Food Service'), ('Other', 'Other')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 19, 10, 35, 53, 718304), help_text='By default its set after 30 days but this can be changed'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='jobapp.category'),
        ),
    ]
