# Generated by Django 4.1.5 on 2023-01-20 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0034_company_alter_job_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='jobapp.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 19, 23, 28, 18, 260198), help_text='By default its set after 30 days but this can be changed'),
        ),
    ]
