# Generated by Django 4.1.5 on 2023-01-20 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0035_job_company_alter_job_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='jobapp.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 19, 23, 29, 15, 80233), help_text='By default its set after 30 days but this can be changed'),
        ),
    ]
