# Generated by Django 4.1.5 on 2023-01-21 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0037_alter_job_last_date_alter_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 20, 13, 46, 11, 176596), help_text='By default its set after 30 days but this can be changed'),
        ),
    ]
