# Generated by Django 4.1.5 on 2023-01-22 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0039_alter_job_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Sales', 'Sales'), ('Management', 'Management'), ('Teaching and Learning', 'Teaching and Learning'), ('Engineering', 'Engineering'), ('Medical and Health', 'Medical and Health'), ('Science', 'Science'), ('Art and Design', 'Art and Design'), ('Legal', 'Legal'), ('Transportation', 'Transportation'), ('Construction', 'Construction'), ('Cleaning', 'Cleaning'), ('Agriculture', 'Agriculture'), ('Food Service', 'Food Service'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 9, 48, 40, 373164), help_text='By default its set after 30 days but this can be changed'),
        ),
    ]
