# Generated by Django 4.1.5 on 2023-01-22 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0040_alter_category_name_alter_job_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 21, 18, 56, 28, 937388), help_text='By default its set after 30 days but this can be changed'),
        ),
    ]
