# Generated by Django 4.1.5 on 2025-05-30 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0044_alter_job_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 29, 8, 22, 12, 922953), help_text='By default its set after 30 days but this can be changed'),
        ),
    ]
